"""Open synthetic databases generated by historical BouncyBot releases."""

from __future__ import annotations

import re
import sqlite3
from pathlib import Path
from typing import Any

import pytest

from app.models import Stage
from app.storage import BotStorage

MIGRATION_FIXTURE_DIR = Path(__file__).resolve().parent / "fixtures" / "migrations"

FIXTURES = {
    "v3.0.19": MIGRATION_FIXTURE_DIR / "v3019_synthetic.sql",
    "v3.1.1": MIGRATION_FIXTURE_DIR / "v311_synthetic.sql",
    "v3.1.2": MIGRATION_FIXTURE_DIR / "v312_synthetic.sql",
}


def _restore_sql_fixture(sql_path: Path, db_path: Path) -> None:
    sql = sql_path.read_text(encoding="utf-8")
    connection = sqlite3.connect(db_path)
    try:
        connection.executescript(sql)
    finally:
        connection.close()


def _schema_snapshot(db_path: Path) -> dict[str, Any]:
    connection = sqlite3.connect(db_path)
    connection.row_factory = sqlite3.Row
    try:
        tables = {
            row["name"]
            for row in connection.execute(
                "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'"
            )
        }
        columns = {
            table: tuple(row["name"] for row in connection.execute(f"PRAGMA table_info({table})"))
            for table in sorted(tables)
        }
        counts = {
            table: int(connection.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0])
            for table in sorted(tables)
        }
        indexes = tuple(
            sorted(
                row["name"]
                for row in connection.execute(
                    "SELECT name FROM sqlite_master WHERE type='index' AND name NOT LIKE 'sqlite_%'"
                )
            )
        )
        return {"columns": columns, "counts": counts, "indexes": indexes}
    finally:
        connection.close()


@pytest.mark.parametrize(("release", "fixture_path"), FIXTURES.items())
def test_historical_database_opens_and_preserves_trading_records(
    tmp_path: Path,
    release: str,
    fixture_path: Path,
) -> None:
    db_path = tmp_path / f"{release}.sqlite"
    _restore_sql_fixture(fixture_path, db_path)

    before = _schema_snapshot(db_path)
    storage = BotStorage(db_path)
    cycle_id = f"v{release.removeprefix('v').replace('.', '')}-synthetic-cycle"
    cycle = storage.get_cycle(cycle_id)

    assert cycle is not None
    assert cycle.ticker == "SYNTH"
    assert cycle.stage == Stage.WAIT_RISE_TRIGGER
    assert cycle.quantity == 10
    assert cycle.buy_filled_qty == 10
    assert cycle.avg_buy_price == pytest.approx(99.5)
    assert cycle.buy_commission == pytest.approx(0.5)
    assert cycle.buy_order_ref == "IBKRBOT|SYNTH|CYCLE-000001|SYNTH001|BUY_TRAIL"

    audit = storage.get_cycle_audit_bundle(cycle_id)
    assert len(audit["orders"]) == 1
    assert len(audit["executions"]) == 1
    assert audit["executions"][0]["execution_id"] == "SYNTH-EXEC-1"
    assert audit["executions"][0]["shares"] == pytest.approx(10.0)
    assert audit["executions"][0]["commission"] == pytest.approx(0.5)

    settings = storage.load_strategy_settings()
    assert settings.ticker == "SYNTH"
    assert settings.currency == "USD"
    assert storage.database_contract_currency() == "USD"

    after = _schema_snapshot(db_path)
    for table in ("cycles", "orders", "executions", "events"):
        assert after["counts"][table] == before["counts"][table]
    assert "buy_remainder_cancel_requested" in after["columns"]["cycles"]
    assert "idx_events_cycle_created" in after["indexes"]
    assert "idx_decision_events_cycle_created" in after["indexes"]


@pytest.mark.parametrize(("release", "fixture_path"), FIXTURES.items())
def test_historical_database_migration_is_idempotent(
    tmp_path: Path,
    release: str,
    fixture_path: Path,
) -> None:
    db_path = tmp_path / f"{release}-idempotent.sqlite"
    _restore_sql_fixture(fixture_path, db_path)

    first = BotStorage(db_path)
    first.database_contract_currency()
    first_snapshot = _schema_snapshot(db_path)

    second = BotStorage(db_path)
    second.database_contract_currency()
    second_snapshot = _schema_snapshot(db_path)

    assert second_snapshot == first_snapshot


def test_historical_fixture_sql_is_synthetic_and_contains_no_private_identifiers() -> None:
    account_token = re.compile(r"\b(?:DU|U)\d{5,}\b", re.IGNORECASE)
    forbidden_paths = ("C:\\Users", "/home/", "/mnt/data/")

    for path in FIXTURES.values():
        text = path.read_text(encoding="utf-8")
        assert "SYNTH" in text
        assert "synthetic migration fixture" in text.lower()
        assert account_token.search(text) is None
        for token in forbidden_paths:
            assert token not in text
